const fs = require('fs');
const path = require('path');

const urlDict = {
  "ChatGPT": "https://chat.openai.com/",
  "GitHub Copilot": "https://github.com/features/copilot",
  "Claude Code": "https://claude.ai/",
  "Amazon Q Developer": "https://aws.amazon.com/q/developer/",
  "Gemini Code Assist": "https://cloud.google.com/gemini/docs/codeassist",
  "Cursor": "https://cursor.sh/",
  "Tabnine": "https://www.tabnine.com/",
  "Codeium": "https://codeium.com/",
  "Cody by Sourcegraph": "https://sourcegraph.com/cody",
  "Devin by Cognition Labs": "https://www.cognition-labs.com/devin",
  "Replit AI": "https://replit.com/ai",
  "v0 by Vercel": "https://v0.dev/",
  "Claude (Anthropic)": "https://anthropic.com/claude",
  "OpenAI GPT models": "https://platform.openai.com/",
  "SillyTavern": "https://github.com/SillyTavern/SillyTavern",
  "Obsidian": "https://obsidian.md/",
  "Smol Developer": "https://github.com/smol-ai/developer",
  "Tabby": "https://tabby.tabbyml.com/",
  "Bloop": "https://bloop.ai/",
  "AskCodi": "https://www.askcodi.com/",
  "Mutable.ai": "https://mutable.ai/",
  "AI Commit": "https://github.com/Nutlope/aicommits",
  "Mintlify": "https://mintlify.com/",
  "WhatTheDiff": "https://whatthediff.ai/",
  "CodeGeeX": "https://codegeex.cn/",
  "FauxPilot": "https://github.com/fauxpilot/fauxpilot",
  "Continue.dev": "https://continue.dev/",
  "LocalAI": "https://localai.io/",
  "Ollama": "https://ollama.ai/",
  "LM Studio": "https://lmstudio.ai/",
  "Postman": "https://www.postman.com/",
  "Insomnia": "https://insomnia.rest/",
  "Swagger": "https://swagger.io/",
  "Apifox": "https://apifox.com/",
  "Hoppscotch": "https://hoppscotch.io/",
  "Bruno": "https://www.usebruno.com/",
  "Paw": "https://paw.cloud/",
  "SoapUI": "https://www.soapui.org/",
  "Mockoon": "https://mockoon.com/",
  "Hasura": "https://hasura.io/",
  "GraphQL Playground": "https://github.com/graphql/graphql-playground",
  "Apollo GraphQL": "https://www.apollographql.com/",
  "Maven": "https://maven.apache.org/",
  "Gradle": "https://gradle.org/",
  "npm": "https://www.npmjs.com/",
  "Yarn": "https://yarnpkg.com/",
  "pnpm": "https://pnpm.io/",
  "pip": "https://pypi.org/project/pip/",
  "Homebrew": "https://brew.sh/",
  "Cargo": "https://doc.rust-lang.org/cargo/",
  "apt (Advanced Package Tool)": "https://wiki.debian.org/Apt",
  "Chocolatey": "https://chocolatey.org/",
  "Poetry": "https://python-poetry.org/",
  "Conda": "https://docs.conda.io/",
  "Go Modules": "https://go.dev/ref/mod",
  "RubyGems": "https://rubygems.org/",
  "Composer": "https://getcomposer.org/",
  "NuGet": "https://www.nuget.org/",
  "Cabal": "https://www.haskell.org/cabal/",
  "Stack": "https://docs.haskellstack.org/",
  "Rake": "https://ruby.github.io/rake/",
  "Bazel": "https://bazel.build/",
  "Buck": "https://buck.build/",
  "Pants": "https://www.pantsbuild.org/",
  "Please": "https://please.build/",
  "Earthly": "https://earthly.dev/",
  "CMake": "https://cmake.org/",
  "Make": "https://www.gnu.org/software/make/",
  "Meson": "https://mesonbuild.com/",
  "AWS (Amazon Web Services)": "https://aws.amazon.com/",
  "Microsoft Azure": "https://azure.microsoft.com/",
  "Google Cloud Platform (GCP)": "https://cloud.google.com/",
  "Oracle Cloud": "https://www.oracle.com/cloud/",
  "Firebase": "https://firebase.google.com/",
  "Supabase": "https://supabase.com/",
  "Vercel": "https://vercel.com/",
  "Netlify": "https://www.netlify.com/",
  "Heroku": "https://www.heroku.com/",
  "DigitalOcean": "https://www.digitalocean.com/",
  "Linode": "https://www.linode.com/",
  "Hetzner": "https://www.hetzner.com/",
  "Cloudflare Workers": "https://workers.cloudflare.com/",
  "Railway": "https://railway.app/",
  "Fly.io": "https://fly.io/",
  "Render": "https://render.com/",
  "Koyeb": "https://www.koyeb.com/",
  "Slack": "https://slack.com/",
  "Microsoft Teams": "https://www.microsoft.com/en-us/microsoft-teams/group-chat-software",
  "Discord": "https://discord.com/",
  "Mattermost": "https://mattermost.com/",
  "Rocket.Chat": "https://rocket.chat/",
  "Zulip": "https://zulip.com/",
  "Docker": "https://www.docker.com/",
  "Kubernetes": "https://kubernetes.io/",
  "Podman": "https://podman.io/",
  "Terraform": "https://www.terraform.io/",
  "Ansible": "https://www.ansible.com/",
  "Puppet": "https://puppet.com/",
  "Chef": "https://www.chef.io/",
  "SaltStack": "https://saltproject.io/",
  "Vagrant": "https://www.vagrantup.com/",
  "Packer": "https://www.packer.io/",
  "Nomad": "https://www.nomadproject.io/",
  "Consul": "https://www.consul.io/",
  "Vault": "https://www.vaultproject.io/",
  "Helm": "https://helm.sh/",
  "Kustomize": "https://kustomize.io/",
  "ArgoCD": "https://argoproj.github.io/cd/",
  "FluxCD": "https://fluxcd.io/",
  "Rancher": "https://rancher.com/",
  "OpenShift": "https://www.redhat.com/en/technologies/cloud-computing/openshift",
  "Docker Compose": "https://docs.docker.com/compose/",
  "GitHub Actions": "https://github.com/features/actions",
  "GitLab CI/CD": "https://docs.gitlab.com/ee/ci/",
  "Jenkins": "https://www.jenkins.io/",
  "CircleCI": "https://circleci.com/",
  "Travis CI": "https://travis-ci.org/",
  "Bitbucket Pipelines": "https://bitbucket.org/product/features/pipelines",
  "Azure Pipelines": "https://azure.microsoft.com/en-us/services/devops/pipelines/",
  "AWS CodePipeline": "https://aws.amazon.com/codepipeline/",
  "Google Cloud Build": "https://cloud.google.com/build",
  "TeamCity": "https://www.jetbrains.com/teamcity/",
  "Bamboo": "https://www.atlassian.com/software/bamboo",
  "Drone": "https://www.drone.io/",
  "Concourse": "https://concourse-ci.org/",
  "Argo Workflows": "https://argoproj.github.io/workflows/",
  "Spinnaker": "https://spinnaker.io/",
  "Octopus Deploy": "https://octopus.com/",
  "Harness": "https://harness.io/",
  "TensorFlow": "https://www.tensorflow.org/",
  "PyTorch": "https://pytorch.org/",
  "Keras": "https://keras.io/",
  "Scikit-learn": "https://scikit-learn.org/",
  "Pandas": "https://pandas.pydata.org/",
  "NumPy": "https://numpy.org/",
  "SciPy": "https://scipy.org/",
  "Matplotlib": "https://matplotlib.org/",
  "Seaborn": "https://seaborn.pydata.org/",
  "Plotly": "https://plotly.com/",
  "Hugging Face": "https://huggingface.co/",
  "Kaggle": "https://www.kaggle.com/",
  "Google Colab": "https://colab.research.google.com/",
  "Azure Machine Learning": "https://azure.microsoft.com/en-us/services/machine-learning/",
  "AWS SageMaker": "https://aws.amazon.com/sagemaker/",
  "Vertex AI": "https://cloud.google.com/vertex-ai",
  "DataRobot": "https://www.datarobot.com/",
  "H2O.ai": "https://h2o.ai/",
  "MySQL": "https://www.mysql.com/",
  "PostgreSQL": "https://www.postgresql.org/",
  "MongoDB": "https://www.mongodb.com/",
  "DBeaver": "https://dbeaver.io/",
  "SQLite": "https://www.sqlite.org/",
  "Redis": "https://redis.io/",
  "Elasticsearch": "https://www.elastic.co/",
  "Apache Cassandra": "https://cassandra.apache.org/",
  "Amazon DynamoDB": "https://aws.amazon.com/dynamodb/",
  "Google Firebase Realtime Database": "https://firebase.google.com/products/realtime-database",
  "Azure Cosmos DB": "https://azure.microsoft.com/en-us/services/cosmos-db/",
  "TablePlus": "https://tableplus.com/",
  "DataGrip": "https://www.jetbrains.com/datagrip/",
  "pgAdmin": "https://www.pgadmin.org/",
  "MySQL Workbench": "https://www.mysql.com/products/workbench/",
  "MongoDB Compass": "https://www.mongodb.com/products/compass",
  "RedisInsight": "https://redis.com/redis-enterprise/redis-insight/",
  "InfluxDB": "https://www.influxdata.com/",
  "Prometheus": "https://prometheus.io/",
  "Grafana": "https://grafana.com/",
  "Tableau": "https://www.tableau.com/",
  "Power BI": "https://powerbi.microsoft.com/",
  "Looker": "https://looker.com/",
  "Apache Spark": "https://spark.apache.org/",
  "Apache Flink": "https://flink.apache.org/",
  "Hadoop": "https://hadoop.apache.org/",
  "Figma": "https://www.figma.com/",
  "Adobe Creative Cloud (Photoshop, Illustrator, etc.)": "https://www.adobe.com/creativecloud.html",
  "Sketch": "https://www.sketch.com/",
  "Adobe XD": "https://www.adobe.com/products/xd.html",
  "InVision": "https://www.invisionapp.com/",
  "Framer": "https://www.framer.com/",
  "Origami Studio": "https://origami.design/",
  "Canva": "https://www.canva.com/",
  "Blender": "https://www.blender.org/",
  "Autodesk Maya": "https://www.autodesk.com/products/maya/",
  "Cinema 4D": "https://www.maxon.net/en/cinema-4d",
  "Krita": "https://krita.org/",
  "Dependabot": "https://github.com/dependabot",
  "Sourcetree": "https://www.sourcetreeapp.com/",
  "GitKraken": "https://www.gitkraken.com/",
  "GitHub Desktop": "https://desktop.github.com/",
  "Fork": "https://git-fork.com/",
  "Oh My Zsh": "https://ohmyz.sh/",
  "iTerm2": "https://iterm2.com/",
  "Hyper": "https://hyper.is/",
  "Windows Terminal": "https://github.com/microsoft/terminal",
  "Alacritty": "https://alacritty.org/",
  "Kitty": "https://sw.kovidgoyal.net/kitty/",
  "Zsh": "https://www.zsh.org/",
  "Fish": "https://fishshell.com/",
  "Bash": "https://www.gnu.org/software/bash/",
  "tldr": "https://tldr.sh/",
  "Cheat.sh": "https://cheat.sh/",
  "Fig": "https://fig.io/",
  "Fzf": "https://github.com/junegunn/fzf",
  "Ripgrep": "https://github.com/BurntSushi/ripgrep",
  "JQ": "https://stedolan.github.io/jq/",
  "YQ": "https://mikefarah.gitbook.io/yq/",
  "HTTPie": "https://httpie.io/",
  "Curl": "https://curl.se/",
  "Wget": "https://www.gnu.org/software/wget/",
  "Exa": "https://the.exa.website/",
  "Bat": "https://github.com/sharkdp/bat",
  "Htop": "https://htop.dev/",
  "Ncdu": "https://dev.yorhel.nl/ncdu",
  "DupeGuru": "https://dupeguru.voltaic.ca/",
  "Alt + Tab": "https://alt-tab-macos.netlify.app/",
  "Rectangle": "https://rectangleapp.com/",
  "Magnet": "https://magnet.crowdcafe.com/",
  "Markdown": "https://daringfireball.net/projects/markdown/",
  "Docusaurus": "https://docusaurus.io/",
  "VuePress": "https://vuepress.vuejs.org/",
  "Read the Docs": "https://readthedocs.org/",
  "Swagger UI": "https://swagger.io/tools/swagger-ui/",
  "GitBook": "https://www.gitbook.com/",
  "MkDocs": "https://www.mkdocs.org/",
  "Sphinx": "https://www.sphinx-doc.org/",
  "Javadoc": "https://docs.oracle.com/javase/8/docs/technotes/tools/windows/javadoc.html",
  "JSDoc": "https://jsdoc.app/",
  "Jupyter Book": "https://jupyterbook.org/",
  "Dash": "https://kapeli.com/dash",
  "Zeal": "https://zealdocs.org/",
  "DevDocs": "https://devdocs.io/",
  "Kapow": "https://github.com/BBVA/kapow",
  "WakaTime": "https://wakatime.com/",
  "Code Climate": "https://codeclimate.com/",
  "Codacy": "https://www.codacy.com/",
  "LGTM": "https://lgtm.com/",
  "Reflect": "https://reflect.run/",
  "LaunchDarkly": "https://launchdarkly.com/",
  "Flagsmith": "https://flagsmith.com/",
  "Split": "https://www.split.io/",
  "ConfigCat": "https://configcat.com/",
  "GrowthBook": "https://www.growthbook.io/",
  "Unity": "https://unity.com/",
  "Unreal Engine": "https://www.unrealengine.com/",
  "Godot": "https://godotengine.org/",
  "CryEngine": "https://www.cryengine.com/",
  "Phaser": "https://phaser.io/",
  "GameMaker Studio": "https://www.yoyogames.com/en/gamemaker",
  "Ren'Py": "https://www.renpy.org/",
  "Construct": "https://www.construct.net/",
  "LibGDX": "https://libgdx.com/",
  "SFML": "https://www.sfml-dev.org/",
  "SDL": "https://www.libsdl.org/",
  "Bevy": "https://bevyengine.org/",
  "Visual Studio Code": "https://code.visualstudio.com/",
  "Visual Studio": "https://visualstudio.microsoft.com/",
  "IntelliJ IDEA": "https://www.jetbrains.com/idea/",
  "PyCharm": "https://www.jetbrains.com/pycharm/",
  "Sublime Text": "https://www.sublimetext.com/",
  "Vim / Neovim": "https://neovim.io/",
  "Eclipse": "https://www.eclipse.org/",
  "Android Studio": "https://developer.android.com/studio",
  "Xcode": "https://developer.apple.com/xcode/",
  "WebStorm": "https://www.jetbrains.com/webstorm/",
  "WindSurf": "https://codeium.com/windsurf",
  "Notepad++": "https://notepad-plus-plus.org/",
  "Jupyter Notebook": "https://jupyter.org/",
  "Rider": "https://www.jetbrains.com/rider/",
  "GoLand": "https://www.jetbrains.com/go/",
  "RubyMine": "https://www.jetbrains.com/ruby/",
  "PhpStorm": "https://www.jetbrains.com/phpstorm/",
  "CLion": "https://www.jetbrains.com/clion/",
  "Zed": "https://zed.dev/",
  "Code::Blocks": "https://www.codeblocks.org/",
  "NetBeans": "https://netbeans.apache.org/",
  "Atom": "https://atom.io/",
  "Brackets": "https://brackets.io/",
  "Geany": "https://www.geany.org/",
  "Emacs": "https://www.gnu.org/software/emacs/",
  "Nano": "https://www.nano-editor.org/",
  "Kate": "https://kate-editor.org/",
  "Bluefish": "https://bluefish.openoffice.nl/",
  "Komodo Edit": "https://www.activestate.com/products/komodo-ide/",
  "EditPlus": "https://www.editplus.com/",
  "UltraEdit": "https://www.ultraedit.com/",
  "Flutter": "https://flutter.dev/",
  "React Native": "https://reactnative.dev/",
  "Ionic": "https://ionicframework.com/",
  "NativeScript": "https://nativescript.org/",
  "Cordova": "https://cordova.apache.org/",
  "Capacitor": "https://capacitorjs.com/",
  "Expo": "https://expo.dev/",
  "Kotlin Multiplatform": "https://kotlinlang.org/docs/multiplatform.html",
  ".NET MAUI": "https://dotnet.microsoft.com/en-us/apps/maui",
  "Xamarin": "https://dotnet.microsoft.com/en-us/apps/xamarin",
  "SwiftUI": "https://developer.apple.com/xcode/swiftui/",
  "Jetpack Compose": "https://developer.android.com/jetpack/compose",
  "Datadog": "https://www.datadoghq.com/",
  "New Relic": "https://newrelic.com/",
  "Sentry": "https://sentry.io/",
  "ELK Stack (Elasticsearch, Logstash, Kibana)": "https://www.elastic.co/what-is/elk-stack",
  "Splunk": "https://www.splunk.com/",
  "Nagios": "https://www.nagios.org/",
  "Zabbix": "https://www.zabbix.com/",
  "Jaeger": "https://www.jaegertracing.io/",
  "Zipkin": "https://zipkin.io/",
  "AppDynamics": "https://www.appdynamics.com/",
  "Dynatrace": "https://www.dynatrace.com/",
  "Loggly": "https://www.loggly.com/",
  "Papertrail": "https://www.papertrail.com/",
  "Sumo Logic": "https://www.sumologic.com/",
  "AWS CloudWatch": "https://aws.amazon.com/cloudwatch/",
  "Azure Monitor": "https://azure.microsoft.com/en-us/services/monitor/",
  "Google Cloud Monitoring": "https://cloud.google.com/monitoring",
  "Zoho Creator": "https://www.zoho.com/creator/",
  "Retool": "https://retool.com/",
  "Appsmith": "https://www.appsmith.com/",
  "Budibase": "https://budibase.com/",
  "ToolJet": "https://tooljet.com/",
  "Mendix": "https://www.mendix.com/",
  "OutSystems": "https://www.outsystems.com/",
  "Power Apps": "https://powerapps.microsoft.com/",
  "Salesforce": "https://www.salesforce.com/",
  "Airtable": "https://airtable.com/",
  "Notion": "https://www.notion.so/",
  "Bubble": "https://bubble.io/",
  "Adalo": "https://www.adalo.com/",
  "Glide": "https://www.glideapps.com/",
  "Softr": "https://www.softr.io/",
  "Caspio": "https://www.caspio.com/",
  "Claris FileMaker": "https://www.claris.com/filemaker/",
  "AppMaster.io": "https://appmaster.io/",
  "Kissflow": "https://kissflow.com/",
  "Jmix": "https://www.jmix.io/",
  "HCL Domino": "https://www.hcltechsw.com/domino",
  "Backstage": "https://backstage.io/",
  "Humanitec": "https://humanitec.com/",
  "Crossplane": "https://crossplane.io/",
  "Kratix": "https://kratix.io/",
  "Porter": "https://porter.run/",
  "Waypoint": "https://www.waypointproject.io/",
  "Kubesphere": "https://kubesphere.io/",
  "Jira": "https://www.atlassian.com/software/jira",
  "Trello": "https://trello.com/",
  "Asana": "https://asana.com/",
  "ClickUp": "https://clickup.com/",
  "Confluence": "https://www.atlassian.com/software/confluence",
  "Linear": "https://linear.app/",
  "Monday.com": "https://monday.com/",
  "Basecamp": "https://basecamp.com/",
  "Pivotal Tracker": "https://www.pivotaltracker.com/",
  "Rally": "https://www.broadcom.com/products/software/agile-development/rally-software",
  "Clubhouse": "https://shortcut.com/",
  "Shortcut": "https://shortcut.com/",
  "Taiga": "https://taiga.io/",
  "OpenProject": "https://www.openproject.org/",
  "Zeplin": "https://zeplin.io/",
  "Miro": "https://miro.com/",
  "AWS Secrets Manager": "https://aws.amazon.com/secrets-manager/",
  "Azure Key Vault": "https://azure.microsoft.com/en-us/services/key-vault/",
  "Google Cloud Secret Manager": "https://cloud.google.com/secret-manager",
  "CyberArk": "https://www.cyberark.com/",
  "1Password": "https://1password.com/",
  "Okta": "https://www.okta.com/",
  "Auth0": "https://auth0.com/",
  "Keycloak": "https://www.keycloak.org/",
  "Firebase Authentication": "https://firebase.google.com/products/auth",
  "OWASP ZAP": "https://www.zaproxy.org/",
  "Burp Suite": "https://portswigger.net/burp",
  "Nmap": "https://nmap.org/",
  "Wireshark": "https://www.wireshark.org/",
  "Metasploit": "https://www.metasploit.com/",
  "Snyk": "https://snyk.io/",
  "WhiteSource": "https://www.mend.io/",
  "Nexus": "https://www.sonatype.com/products/nexus-repository",
  "Tines": "https://www.tines.com/",
  "Akamai": "https://www.akamai.com/",
  "Cloudflare": "https://www.cloudflare.com/",
  "Incogni": "https://incogni.com/",
  "Mullvad": "https://mullvad.net/",
  "ProtonMail": "https://proton.me/mail",
  "Tutanota": "https://tuta.com/",
  "Signal": "https://signal.org/",
  "Telegram": "https://telegram.org/",
  "Cypress": "https://www.cypress.io/",
  "Jest": "https://jestjs.io/",
  "Selenium": "https://www.selenium.dev/",
  "JUnit": "https://junit.org/",
  "PyTest": "https://docs.pytest.org/",
  "Mocha": "https://mochajs.org/",
  "Chai": "https://www.chaijs.com/",
  "WebDriverIO": "https://webdriver.io/",
  "Karma": "https://karma-runner.github.io/",
  "TestCafe": "https://testcafe.io/",
  "Playwright": "https://playwright.dev/",
  "Puppeteer": "https://pptr.dev/",
  "PHPUnit": "https://phpunit.de/",
  "NUnit": "https://nunit.org/",
  "xUnit.net": "https://xunit.net/",
  "Robot Framework": "https://robotframework.org/",
  "Appium": "https://appium.io/",
  "Detox": "https://wix.github.io/Detox/",
  "Cucumber": "https://cucumber.io/",
  "Gherkin": "https://cucumber.io/docs/gherkin/",
  "SonarQube": "https://www.sonarqube.org/",
  "ESLint": "https://eslint.org/",
  "Prettier": "https://prettier.io/",
  "Stylelint": "https://stylelint.io/",
  "JMeter": "https://jmeter.apache.org/",
  "LoadRunner": "https://www.microfocus.com/en-us/products/loadrunner-professional/overview",
  "Gatling": "https://gatling.io/",
  "k6": "https://k6.io/",
  "Git": "https://git-scm.com/",
  "GitHub": "https://github.com/",
  "GitLab": "https://about.gitlab.com/",
  "Bitbucket": "https://bitbucket.org/",
  "SVN (Apache Subversion)": "https://subversion.apache.org/",
  "Mercurial": "https://www.mercurial-scm.org/",
  "Perforce Helix": "https://www.perforce.com/products/helix-core",
  "Azure Repos": "https://azure.microsoft.com/en-us/services/devops/repos/",
  "AWS CodeCommit": "https://aws.amazon.com/codecommit/",
  "React": "https://reactjs.org/",
  "Vue.js": "https://vuejs.org/",
  "Angular": "https://angular.io/",
  "Svelte": "https://svelte.dev/",
  "Next.js": "https://nextjs.org/",
  "Nuxt.js": "https://nuxtjs.org/",
  "Astro": "https://astro.build/",
  "Gatsby": "https://www.gatsbyjs.com/",
  "Remix": "https://remix.run/",
  "Tailwind CSS": "https://tailwindcss.com/",
  "Bootstrap": "https://getbootstrap.com/",
  "Material-UI": "https://mui.com/",
  "Chakra UI": "https://chakra-ui.com/",
  "Ant Design": "https://ant.design/",
  "Semantic UI": "https://semantic-ui.com/",
  "Django": "https://www.djangoproject.com/",
  "Ruby on Rails": "https://rubyonrails.org/",
  "Spring Boot": "https://spring.io/projects/spring-boot",
  "Express.js": "https://expressjs.com/",
  "ASP.NET Core": "https://dotnet.microsoft.com/en-us/apps/aspnet",
  "Flask": "https://flask.palletsprojects.com/",
  "Laravel": "https://laravel.com/",
  "FastAPI": "https://fastapi.tiangolo.com/",
  "Node.js": "https://nodejs.org/",
  "Deno": "https://deno.land/",
  "Bun": "https://bun.sh/",
  "NestJS": "https://nestjs.com/",
  "Phoenix": "https://www.phoenixframework.org/",
  "Actix-web": "https://actix.rs/",
  "Rocket": "https://rocket.rs/",
  "Gin": "https://gin-gonic.com/",
  "Echo": "https://echo.labstack.com/"
};

const devDir = 'c:/Users/Bonnie/Desktop/MR. BIT TOOLS/src/pages/development';
const dirs = fs.readdirSync(devDir);

dirs.forEach(dir => {
  const dirPath = path.join(devDir, dir);
  if (!fs.statSync(dirPath).isDirectory()) return;
  
  const files = fs.readdirSync(dirPath);
  
  // 1. Process Data file
  const dataFile = files.find(f => f.endsWith('Data.ts'));
  if (dataFile) {
    let content = fs.readFileSync(path.join(dirPath, dataFile), 'utf8');
    
    // Add url?: string to DevItem
    if (!content.includes('url?: string') && !content.includes('url: string')) {
      content = content.replace(/export interface DevItem\s*\{([^}]+)\}/g, (match, p1) => {
        return `export interface DevItem {${p1}  url?: string;\n}`;
      });
    }

    // Replace items
    content = content.replace(/\{(\s*name:\s*\"([^\"]+)\"\s*,\s*desc:\s*\"([^\"]+)\"\s*)\}/g, (match, inner, name, desc) => {
      let url = urlDict[name];
      if (!url) {
        url = 'https://www.google.com/search?q=' + encodeURIComponent(name + ' tool');
      }
      return '{ name: "' + name + '", desc: "' + desc + '", url: "' + url + '" }';
    });

    fs.writeFileSync(path.join(dirPath, dataFile), content);
  }

  // 2. Process Component file
  const compFile = files.find(f => f.endsWith('.tsx'));
  if (compFile) {
    let content = fs.readFileSync(path.join(dirPath, compFile), 'utf8');
    
    // Add ArrowUpRight import
    if (!content.includes('ArrowUpRight')) {
      content = content.replace(/import \{ Code \} from 'lucide-react';/g, "import { Code, ArrowUpRight } from 'lucide-react';");
    }

    // Update JSX
    const oldJsx = /<div key=\{item\.name\} className=\{\`\$\{styles\.card\} glass\`\}>\s*<h4>\{item\.name\}<\/h4>/;
    const newJsx = `<div key={item.name} className={\`\${styles.card} glass\`}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                <h4>{item.name}</h4>
                {item.url && (
                  <a href={item.url} target="_blank" rel="noopener noreferrer" style={{ color: 'var(--text-secondary)' }}>
                    <ArrowUpRight size={18} />
                  </a>
                )}
              </div>`;
              
    content = content.replace(oldJsx, newJsx);
    fs.writeFileSync(path.join(dirPath, compFile), content);
  }
});

console.log('Successfully injected URLs and updated components!');
