export interface ExternalTool {
  name: string;
  url: string;
  description: string;
  category: string;
  starred?: boolean;
}

export const EXTERNAL_TOOLS: ExternalTool[] = [
  // Productivity
  { name: 'ASCIIFlow', url: 'https://asciiflow.com/', description: 'An application for drawing ASCII diagrams', category: 'Productivity' },
  { name: 'BentoPDF', url: 'https://www.bentopdf.com/', description: 'Powerful, privacy-first, client-side PDF toolkit that is self hostable and allows you to manipulate, edit, merge, and process PDF files', category: 'Productivity', starred: true },
  { name: 'CryptPad', url: 'https://cryptpad.fr', description: 'Collaborative office suite, end-to-end encrypted and open-source.', category: 'Productivity', starred: true },
  { name: 'DoHabit', url: 'https://dohabit.app/', description: 'Lightweight, local-first habit tracker designed to respect your privacy', category: 'Productivity' },
  { name: 'dSheets', url: 'https://dsheets.new/', description: 'dsheets.new is alternative to google sheets & excel.', category: 'Productivity' },
  { name: 'EtherCalc', url: 'https://ethercalc.net/', description: 'Spreadsheet for real-time collaborative editing', category: 'Productivity' },
  { name: 'flowchart.fun', url: 'https://flowchart.fun/', description: 'Easily generate flowcharts and diagrams from text', category: 'Productivity' },
  { name: 'Grist', url: 'https://docs.getgrist.com', description: 'Modern relational spreadsheet. It combines the flexibility of a spreadsheet with the robustness of a database', category: 'Productivity', starred: true },
  { name: 'Lanjut', url: 'https://lanjut.rimzzlabs.com', description: 'ATS-Friendly Resume Builder', category: 'Productivity', starred: true },
  { name: 'Mermify', url: 'https://tra-sco.github.io/mermify/', description: 'Bi-directional visual editor for Mermaid.js flowcharts', category: 'Productivity' },
  { name: 'MiroTalk P2P', url: 'https://p2p.mirotalk.com/', description: 'WebRTC video conferencing platform built on peer-to-peer (P2P) architecture for fast, secure real-time communication with end-to-end privacy', category: 'Productivity' },
  { name: 'Monkeytype', url: 'https://monkeytype.com/', description: 'The most customizable typing website with a minimalistic design and a ton of features. Test yourself in various modes, track your progress and improve your speed', category: 'Productivity' },
  { name: 'Postbaby', url: 'https://postbaby.org/', description: 'Provides a board for quick little notes post-it like', category: 'Productivity' },
  { name: 'QuickRetro', url: 'https://quickretro.app/', description: 'Real-time app for conducting a remote sprint retrospective meeting', category: 'Productivity' },
  { name: 'Resume Nation', url: 'https://resume-nation.github.io', description: 'Progressive resume builder which works offline', category: 'Productivity' },
  { name: 'Sipp Chat', url: 'https://chat.sipp.sh/', description: 'AI inference, packed simply. A blazing-fast, zero-dependency WebGPU runtime to run GGUF models directly in the browser', category: 'Productivity' },
  { name: 'Stirling-PDF', url: 'https://stirling.com/app', description: '#1 PDF Application on GitHub that lets you edit PDFs on any device anywhere', category: 'Productivity' },
  { name: 'Tailit', url: 'https://tailit.xyz/', description: 'An interactive resume builder with templates. Paste a job link and AI rewrites your resume to match', category: 'Productivity' },
  { name: 'Tomodoro', url: 'https://lazy-guy.github.io/tomodoro/', description: 'A pomodoro web app with PIP mode, white noise generation, tasks and more!', category: 'Productivity' },
  { name: 'WebLLM', url: 'https://webllm.mlc.ai/', description: 'High-performance In-browser LLM Inference Engine', category: 'Productivity', starred: true },

  // Design & Graphics
  { name: 'Avnac', url: 'https://avnac.design/', description: 'Design editor for posters, layouts, social graphics, and other canvas-based compositions', category: 'Design & Graphics' },
  { name: 'Blockbench', url: 'https://web.blockbench.net/', description: 'A low poly 3D model editor', category: 'Design & Graphics' },
  { name: 'ColorKit', url: 'https://colorskit.vercel.app/', description: 'Feature-rich color picker and analysis tool', category: 'Design & Graphics' },
  { name: 'Component Gallery', url: 'https://component.gallery/', description: 'The Component Gallery is a collection of components from the best Design Systems.', category: 'Design & Graphics' },
  { name: 'Darkly.Art', url: 'https://darkly.art/', description: 'Entropic Editor for Artists', category: 'Design & Graphics' },
  { name: 'Dashboard Icons', url: 'https://dashboardicons.com/', description: 'A collection of over 1800 curated icons for services, applications and tools, designed specifically for dashboards and app directories', category: 'Design & Graphics' },
  { name: 'Design Systems Checklist', url: 'https://designsystemchecklist.com/', description: 'Checklist to help you plan, build and grow your design system', category: 'Design & Graphics' },
  { name: 'dither', url: 'https://dither.fuego.im/', description: 'Pixel-perfect dithering utility. Drop an image, dial in the settings, ship a dither', category: 'Design & Graphics' },
  { name: 'draw.io', url: 'https://www.drawio.com/', description: 'A configurable browser-based diagramming and whiteboarding tool for flowcharts, UML, network diagrams, ER diagrams, BPMN, and more.', category: 'Design & Graphics' },
  { name: 'DrawShare', url: 'https://shravangoswami.com/DrawShare/', description: 'Collaborative whiteboard for drawing and note-taking', category: 'Design & Graphics' },
  { name: 'Excalidraw', url: 'https://excalidraw.com', description: 'Virtual whiteboard for sketching hand-drawn like diagrams', category: 'Design & Graphics', starred: true },
  { name: 'Fluid', url: 'https://fluid.krackeddevs.com/', description: 'Dependency-free WebGL studio for generative backgrounds and live embeds', category: 'Design & Graphics', starred: true },
  { name: 'Glyphr Studio', url: 'https://www.glyphrstudio.com/', description: 'Font editor, made for hobbyists and typeface design beginners', category: 'Design & Graphics' },
  { name: 'GodSVG', url: 'https://www.godsvg.com/editor/', description: 'Structured SVG editor', category: 'Design & Graphics' },
  { name: 'Graphite', url: 'https://editor.graphite.rs', description: 'Community-built comprehensive 2D content creation application powered by a node-based procedural graphics engine', category: 'Design & Graphics', starred: true },
  { name: 'Icon Maker', url: 'https://ray.so/icon', description: 'Tool that lets you quickly generate clean, professional app icons using customizable shapes, gradients, and glyphs', category: 'Design & Graphics' },
  { name: 'Image to UnicodeASCII Generator', url: 'https://reactorcore.itch.io/image-to-unicodeascii-generator', description: 'Easily transform any image into ASCII/Unicode art', category: 'Design & Graphics' },
  { name: 'JSPaint', url: 'https://jspaint.app', description: 'Classic MS Paint, REVIVED + Extras', category: 'Design & Graphics', starred: true },
  { name: 'Klecks', url: 'https://kleki.com/', description: 'Modern and feature-rich painting app for the web', category: 'Design & Graphics' },
  { name: 'MakeGirlsMoe', url: 'https://make.girls.moe', description: 'Create Anime Characters', category: 'Design & Graphics' },
  { name: 'Method Draw', url: 'https://editor.method.ac', description: 'Simple and easy-to-use SVG editor experience', category: 'Design & Graphics' },
  { name: 'OpenMosh', url: 'https://open-mosh.vercel.app/', description: 'Datamosh your photos and videos, glitch effects in sync with music.', category: 'Design & Graphics' },
  { name: 'Pattern Craft', url: 'https://patterncraft.store/', description: 'Professional-grade background patterns and gradients for your websites and apps', category: 'Design & Graphics' },
  { name: 'Phosphor-Cam', url: 'https://phosphor-cam.vercel.app/', description: 'Real-time ASCII art camera that transforms your webcam feed into glowing terminal aesthetics.', category: 'Design & Graphics' },
  { name: 'Piskel', url: 'https://www.piskelapp.com', description: 'Easy-to-use sprite editor. It can be used to create game sprites, animations, and pixel-art', category: 'Design & Graphics' },
  { name: 'PixelCraft', url: 'https://pixelcraft.web.app', description: 'A pixel Art & Animation Creation Tool Built using HTML5 Canvas', category: 'Design & Graphics' },
  { name: 'Pixelorama', url: 'https://orama-interactive.itch.io/pixelorama', description: 'Create pixel art in your browser', category: 'Design & Graphics' },
  { name: 'Planar', url: 'https://planar.masn.studio', description: 'A client-side web utility to scale, crop, and tile images onto sheets of paper for printing at exact real-world dimensions.', category: 'Design & Graphics' },
  { name: 'Screenshot Studio', url: 'https://www.screenshot-studio.com/', description: 'A free, browser-based screenshot editor with beautiful backgrounds, device frames, and 3D effects.', category: 'Design & Graphics', starred: true },
  { name: 'ShadeStudio', url: 'https://laura.media/shade-studio/', description: 'Create a full color palette from a base color and export it to CSS, Tailwind and SVG', category: 'Design & Graphics' },
  { name: 'Studio', url: 'https://studio.neato.fun/', description: 'A suite of random, mostly weird, generative art tools!', category: 'Design & Graphics' },
  { name: 'SVG-Edit', url: 'https://svgedit.netlify.app/index.html', description: 'Powerful SVG-Editor for your browser', category: 'Design & Graphics' },
  { name: 'SvgPathEditor', url: 'https://yqnn.github.io/svg-path-editor/', description: 'Online editor to create and manipulate SVG paths', category: 'Design & Graphics' },
  { name: 'TerraInk', url: 'https://terraink.app/', description: 'Cartographic poster engine', category: 'Design & Graphics' },
  { name: 'TheSVG', url: 'https://thesvg.org/', description: '6,100+ SVG icons. Brands, AWS, Azure, GCP, and more. Search, copy, ship.', category: 'Design & Graphics' },
  { name: 'tldraw', url: 'https://www.tldraw.com/', description: 'A simple drawing/whiteboarding tool', category: 'Design & Graphics' },
  { name: 'ToolsForImage', url: 'https://toolsforimage.com/', description: 'Web application that provides a suite of image processing tools', category: 'Design & Graphics' },
  { name: 'Unicon', url: 'https://unicon-tool.vercel.app/', description: 'Convert any Unicode symbol, emoji, or glyph into a custom favicon', category: 'Design & Graphics' },
  { name: 'Vecto3d', url: 'https://vecto3d.app/', description: 'A super simple tool to convert your SVGs to 3D models', category: 'Design & Graphics' },
  { name: 'VoidMesh', url: 'https://voidmesh.xyz/', description: 'Local image and video filters with shaders, on an infinite canvas', category: 'Design & Graphics' },
  { name: 'Word Aligner', url: 'https://aligner.tinygods.dev', description: 'Link words across a translation, then export the diagram.', category: 'Design & Graphics' },

  // Development
  { name: 'Algorithm Visualizer', url: 'https://algorithm-visualizer.org/', description: 'An interactive online platform for visualizing algorithms from code and learning algorithm behavior through animations.', category: 'Development' },
  { name: 'Amicro', url: 'https://amicro.vercel.app/', description: 'A curated library of premium React micro-interactions and transition components powered by Motion.', category: 'Development' },
  { name: 'App Store Web Search', url: 'https://vexelon.net/asws', description: 'A web app that enables you to search the Apple App Store in your browser and view app meta-data.', category: 'Development' },
  { name: 'ASM Editor', url: 'https://asm-editor.specy.app', description: 'A web editor to write, run and learn assembly code (X86, MIPS, RISC-V, M68K)', category: 'Development' },
  { name: 'AST explorer', url: 'https://astexplorer.net/', description: 'A web tool to explore the ASTs generated by various parsers.', category: 'Development' },
  { name: 'BezierMotion', url: 'https://tughloks.github.io/BezierMotion/', description: 'A visual cubic-bezier curve editor for crafting custom CSS easing functions', category: 'Development' },
  { name: 'Bundlephobia', url: 'https://bundlephobia.com/', description: 'Find out the cost of adding a new frontend dependency to your project', category: 'Development' },
  { name: 'carbon', url: 'https://carbon.now.sh/', description: 'Create and share beautiful images of your source code', category: 'Development' },
  { name: 'CheckMyGit', url: 'https://checkmygit.com/', description: 'Transform any GitHub profile into a stunning portfolio in seconds.', category: 'Development' },
  { name: 'CircuitJS1', url: 'https://www.falstad.com/circuit/', description: 'A browser-based electronic circuit simulator with animated schematics.', category: 'Development' },
  { name: 'CodeGraphContext (CGC)', url: 'https://cgc.codes/explore', description: 'Indexes local code into a graph database to provide context to AI assistants', category: 'Development' },
  { name: 'CodeMap AI', url: 'https://code-map-ai-mu.vercel.app/', description: 'Helps developers, especially beginners in open source, understand large repositories faster.', category: 'Development' },
  { name: 'CSV Repair', url: 'https://www.csv.repair/', description: 'A free, browser-based tool for analyzing, querying, and repairing broken or oversized CSV files', category: 'Development' },
  { name: 'DartPad', url: 'https://dartpad.dev', description: 'An online Dart editor with support for console, web, and Flutter apps.', category: 'Development' },
  { name: 'delphitools', url: 'https://delphi.tools/', description: 'A collection of small, low stakes and low effort tools', category: 'Development' },
  { name: 'drawDB', url: 'https://www.drawdb.app', description: 'Free, simple, and intuitive online database diagram editor and SQL generator', category: 'Development', starred: true },
  { name: 'explainshell.com', url: 'https://explainshell.com/', description: 'Match command-line arguments to their help text', category: 'Development' },
  { name: 'FaviconAPI', url: 'https://faviconapi.com', description: 'Get the highest resolution favicon for any domain or look up a service icon by name.', category: 'Development' },
  { name: 'Feather', url: 'https://feathericons.com/', description: 'Simply beautiful open-source icons', category: 'Development' },
  { name: 'FFmpeg CLI Online', url: 'https://ffmpeg.wide.video', description: 'Run ffmpeg directly in your browser with a terminal-like interface.', category: 'Development' },
  { name: 'ffmpeg.wasm', url: 'https://ffmpegwasm.netlify.app/playground', description: 'FFmpeg for browser, powered by WebAssembly', category: 'Development' },
  { name: 'Gately', url: 'https://www.gately.dev/', description: 'Simple and modern web-based logic gate simulator', category: 'Development' },
  { name: 'gists.sh', url: 'https://gists.sh/', description: 'Create and share beautifully styled GitHub Gists, code, notes, and snippets.', category: 'Development' },
  { name: 'GitFut', url: 'https://gitfut.com/', description: 'Your GitHub profile rated and analyzed.', category: 'Development' },
  { name: 'heroicons', url: 'https://heroicons.com/', description: 'A set of free MIT-licensed high-quality SVG icons for UI development.', category: 'Development' },
  { name: 'hoppscotch', url: 'https://hoppscotch.io/', description: 'Open-Source API Development Ecosystem. Alternative to Postman.', category: 'Development', starred: true },
  { name: 'Iconoir', url: 'https://iconoir.com/', description: 'An open source icons library with 1600+ icons, supporting React, Vue, Figma, and Framer.', category: 'Development' },
  { name: 'IT-Tools', url: 'https://it-tools.tech/', description: 'Collection of handy online tools for developers, with great UX', category: 'Development' },
  { name: 'JS Bin', url: 'https://jsbin.com', description: 'Collaborative JavaScript Debugging App', category: 'Development' },
  { name: 'JSON Crack', url: 'https://jsoncrack.com/', description: 'Visualization application that transforms JSON, YAML, XML and CSV into interactive graphs', category: 'Development' },
  { name: 'KiCanvas', url: 'https://kicanvas.org/', description: 'An interactive browser-based viewer for KiCad schematics and PCB boards.', category: 'Development' },
  { name: 'Kroki', url: 'https://kroki.io/#try', description: 'Diagram rendering service that generates diagrams from text.', category: 'Development' },
  { name: 'Log Voyager', url: 'https://www.logvoyager.cc/', description: 'Analyze huge log files (10GB+). Features JSON prettifier, regex filtering, and bookmarks.', category: 'Development' },
  { name: 'Lucide', url: 'https://lucide.dev/', description: 'Beautiful & consistent icon toolkit made by the community', category: 'Development' },
  { name: 'Markmap', url: 'https://markmap.js.org/', description: 'Creates interactive mind maps from Markdown with a live editor', category: 'Development' },
  { name: 'Mermaid Live', url: 'https://mermaid.live', description: 'Edit, preview and share mermaid charts/diagrams.', category: 'Development' },
  { name: 'Niolesk', url: 'http://niolesk.top', description: 'Edit diagrams from textual descriptions!', category: 'Development' },
  { name: 'Online Maven Download Tool', url: 'https://maven-tools.mohants.com/', description: 'Download Maven JAR dependencies and transitive dependencies as ZIP', category: 'Development' },
  { name: 'Online tools', url: 'https://emn178.github.io/online-tools/', description: 'Provides hashing, encoding, decoding, escaping, and formatting utilities', category: 'Development' },
  { name: 'OpenCode Config Builder', url: 'https://openconfig.mikescave.us', description: 'Configuration builder/editor for opencode.', category: 'Development' },
  { name: 'Openhero', url: 'https://openhero.art/', description: 'Collection of cinematic video hero sections. Browse, preview, and download backgrounds.', category: 'Development' },
  { name: 'OpenMoji', url: 'https://openmoji.org/library/', description: 'Open source emojis for designers, developers and everyone else!', category: 'Development' },
  { name: 'Phosphor Icons', url: 'https://ionic.io/ionicons', description: 'A flexible icon family for designers and developers.', category: 'Development' },
  { name: 'Python Tutor', url: 'https://pythontutor.com', description: 'Visualize code execution step-by-step to better understand programming concepts.', category: 'Development' },
  { name: 'QuickRef.ME', url: 'https://quickref.me/', description: 'Share quick reference cheat sheet for developers', category: 'Development' },
  { name: 'RegExr', url: 'https://regexr.com/', description: 'HTML/JS based tool for creating, testing, and learning about Regular Expressions', category: 'Development', starred: true },
  { name: 'Remix Icons', url: 'https://remixicon.com/', description: 'Open source neutral style icon system', category: 'Development' },
  { name: 'Rom Patcher JS', url: 'https://www.marcrobledo.com/RomPatcher.js/', description: 'A ROM patcher made in Javascript', category: 'Development' },
  { name: 'ROOC Optimization', url: 'https://rooc.specy.app/', description: 'A web platform for modelling and solving linear optimization problems', category: 'Development' },
  { name: 'Scratch Tabs', url: 'https://app.scratchtabs.com/', description: 'Local-first developer workspace for exploring, transforming, and validating text/data formats', category: 'Development' },
  { name: 'selfh.st Icons', url: 'https://selfh.st/icons/', description: 'Dashboard Icons provided by selfh.st', category: 'Development' },
  { name: 'Simple Icons', url: 'https://simpleicons.org/', description: 'Free SVG icons for popular brands. 3000+ icons, public domain.', category: 'Development' },
  { name: 'Sqlime', url: 'https://sqlime.org/', description: 'Online SQLite playground', category: 'Development' },
  { name: 'SVGOMG', url: 'https://jakearchibald.github.io/svgomg/', description: 'Shrink SVG sizes dramatically', category: 'Development' },
  { name: 'Tabler Icons', url: 'https://tabler.io/icons', description: 'A set of over 6000 free MIT-licensed high-quality SVG icons.', category: 'Development' },
  { name: 'Tokeko', url: 'https://tokeko.specy.app/', description: 'An online creation tool for LALR and LR(1) parsers', category: 'Development' },
  { name: 'Transform', url: 'https://transform.tools/', description: 'A polyglot web converter', category: 'Development' },
  { name: 'VeriSim', url: 'https://senolgulgonul.github.io/verisim/', description: 'Verilog simulator built by compiling Icarus Verilog to WebAssembly.', category: 'Development' },
  { name: 'Visual Studio Code for the Web', url: 'https://vscode.dev/', description: 'Free, zero-install VS Code running entirely in your browser.', category: 'Development' },

  // Writing & Docs
  { name: 'AFFiNE', url: 'https://affine.pro/', description: 'Next-gen knowledge base that brings planning, sorting and creating all together', category: 'Writing & Docs' },
  { name: 'Browserpad', url: 'https://browserpad.org', description: 'Plain text editor in the browser.', category: 'Writing & Docs' },
  { name: 'dDocs', url: 'https://ddocs.new/', description: 'A privacy-first, end-to-end encrypted alternative to Google Docs.', category: 'Writing & Docs' },
  { name: 'Dillinger', url: 'https://dillinger.io', description: '"The last Markdown editor, ever."', category: 'Writing & Docs' },
  { name: 'EasyPeasyCV', url: 'https://easypeasycv.com/', description: 'Resume builder designed for professionals who value privacy and control over data', category: 'Writing & Docs' },
  { name: 'EditorPilot', url: 'https://editorpilot.com/', description: 'AI writing assistant that lives entirely in your browser', category: 'Writing & Docs' },
  { name: 'Free CV Builder', url: 'https://buildmyfree.cv/', description: 'Build a professional CV in a few minutes and download it as a PDF', category: 'Writing & Docs' },
  { name: 'GoatPad', url: 'https://goatpad.drexfall.com/', description: 'A notepad for the web written in Flutter', category: 'Writing & Docs' },
  { name: 'Koodo Reader', url: 'https://web.koodoreader.com/', description: 'A modern ebook manager and reader', category: 'Writing & Docs' },
  { name: 'Linwood Butterfly', url: 'https://web.butterfly.linwood.dev/', description: 'Powerful, minimalistic note-taking app', category: 'Writing & Docs' },
  { name: 'Logseq', url: 'https://logseq.com/', description: 'A privacy-first, open-source platform for knowledge management.', category: 'Writing & Docs', starred: true },
  { name: 'lookscanned', url: 'https://lookscanned.io', description: 'Turn PDFs and documents into realistic scanned copies locally.', category: 'Writing & Docs' },
  { name: 'Markdown Live Preview', url: 'https://markdownlivepreview.com', description: 'Markdown editor with live preview', category: 'Writing & Docs' },
  { name: 'markdown2pdf', url: 'https://markdown2pdfconverter.vercel.app/', description: 'A markdown to PDF converter & live previewer', category: 'Writing & Docs' },
  { name: 'Notepad PWA', url: 'https://notepad.js.org', description: 'An offline capable Notepad PWA', category: 'Writing & Docs' },
  { name: 'StackEdit', url: 'https://stackedit.io', description: 'Full-featured markdown editor', category: 'Writing & Docs', starred: true },
  { name: 'Strong Editor', url: 'https://strongeditor.com/', description: 'Text editor that highlights poor wording in real-time', category: 'Writing & Docs' },
  { name: 'Universal Résumé Template', url: 'https://universalresume.app/?s=g', description: 'Minimal and formal résumé (CV) website template', category: 'Writing & Docs' },

  // Privacy & Security
  { name: 'Cryptgeon', url: 'https://cryptgeon.com/', description: 'Send fully encrypted secure notes or files with custom expiration', category: 'Privacy & Security' },
  { name: 'Cryptii', url: 'https://cryptii.com', description: 'App for modular conversion, encoding, and encryption', category: 'Privacy & Security' },
  { name: 'CyberChef', url: 'https://gchq.github.io/CyberChef/', description: 'A browser-based cyber workbench for encryption, hashing, and parsing recipes.', category: 'Privacy & Security' },
  { name: 'image-scrubber', url: 'https://everestpipkin.github.io/image-scrubber/', description: 'A tool for anonymizing photographs taken at protests', category: 'Privacy & Security' },
  { name: 'Metadata Remover', url: 'https://ianonymous3000.github.io/metadata-remover/', description: 'Removes metadata from supported formats in-browser using WASM', category: 'Privacy & Security' },
  { name: 'privacy.sexy', url: 'https://privacy.sexy', description: 'Enforce privacy & security best-practices on Windows, macOS and Linux.', category: 'Privacy & Security', starred: true },
  { name: 'ProtegeMiDNI', url: 'https://protegemidni.es', description: 'Redact non-essential info from national identification documents.', category: 'Privacy & Security' },
  { name: 'ShareClean', url: 'https://omarh-creator.github.io/ShareClean/#playground', description: 'Sanitize logs, stack traces, and snippets before sharing them.', category: 'Privacy & Security' },

  // Utilities
  { name: 'BottleShip', url: 'https://bottleship.pages.dev/', description: 'Run classic Windows games in your browser', category: 'Utilities', starred: true },
  { name: 'BRouter-web', url: 'https://brouter.de/brouter-web/', description: 'OpenStreetMap-based route planning with profile customization.', category: 'Utilities' },
  { name: 'CheezyPizza', url: 'https://file.pizza/', description: 'WebRTC based p2p file transfers in your browser', category: 'Utilities' },
  { name: 'Clip Fish', url: 'https://clip.fish/', description: 'App for quickly sharing links, text snippets, and files.', category: 'Utilities' },
  { name: 'Convert To It', url: 'http://convert.to.it/', description: 'Truly universal online file converter', category: 'Utilities' },
  { name: 'Daggerheart GM Screen', url: 'https://jutier.github.io/Daggerheart/', description: 'Daggerheart GM Screen', category: 'Utilities' },
  { name: 'DropSilk', url: 'https://www.dropsilk.xyz/', description: 'Modern, privacy-focused, peer-to-peer WebRTC file transfer application', category: 'Utilities' },
  { name: 'e2ecp', url: 'https://e2ecp.com', description: 'Transfer files end-to-end encrypted in your browser or command line.', category: 'Utilities' },
  { name: 'Enclosed', url: 'https://enclosed.cc/', description: 'Send end-to-end encrypted notes and files safely.', category: 'Utilities' },
  { name: 'ente Paste', url: 'https://paste.ente.com/', description: 'Share text between devices securely with QR code or URL', category: 'Utilities' },
  { name: 'enumbers lookup', url: 'https://enumbers.jarvisdiscordbot.net/', description: 'Lookup E-number food additives with Open Food Facts data.', category: 'Utilities' },
  { name: 'FileDrop', url: 'https://drop.lol/', description: 'End-to-end encrypted peer-to-peer file transfer and chat', category: 'Utilities' },
  { name: 'Giraffile', url: 'https://giraffile.pages.dev/', description: 'Share files quickly and securely without relying on cloud servers', category: 'Utilities' },
  { name: 'Gridfinity Layout Tool', url: 'https://gridfinitylayouttool.com', description: 'A tool for planning drawer organization using the Gridfinity system', category: 'Utilities' },
  { name: 'Jobber', url: 'https://rssjobs.app/', description: 'Dynamic Job Search RSS Feed Generator', category: 'Utilities' },
  { name: 'kPaste', url: 'https://kpaste.infomaniak.com/', description: 'Private end-to-end encrypted pastebin', category: 'Utilities' },
  { name: 'LocalSend-Web', url: 'https://web.localsend.org/', description: 'Open-source local network file sharing alternative to AirDrop.', category: 'Utilities', starred: true },
  { name: 'Open-RazerKit', url: 'https://hamzayslmn.github.io/open-razerkit/', description: "Control your Razer device's RGB, effects, and settings", category: 'Utilities' },
  { name: 'OpenReader', url: 'https://openreader.richardr.dev/app', description: 'Text-to-speech document reader with multilingual read-along playback', category: 'Utilities' },
  { name: 'Oscilloscope Online V2', url: 'https://mumarshahbaz.github.io/Oscilloscope-Online-V2/setup.html', description: 'Web Serial Plotter with full customization options', category: 'Utilities' },
  { name: 'OwnCardly', url: 'https://owncardly.com/', description: 'Digital business cards you actually own', category: 'Utilities' },
  { name: 'PairDrop', url: 'https://pairdrop.net/', description: 'Transfer Files Cross-Platform. No Setup, No Signup.', category: 'Utilities', starred: true },
  { name: 'Pandoc WASM', url: 'https://pandoc.github.io/pandoc-wasm/', description: 'Convert documents without leaving the browser.', category: 'Utilities' },
  { name: 'PaperKnife', url: 'https://potatameister.github.io/PaperKnife/', description: 'Merge, split, compress, and edit PDFs 100% locally on your device', category: 'Utilities' },
  { name: 'QRazyBox', url: 'https://merricx.github.io/qrazybox/', description: 'Recover and analyze damaged QR Codes.', category: 'Utilities' },
  { name: 'QrCodeShow', url: 'https://qrcode.show/', description: 'Generate QR codes easily', category: 'Utilities' },
  { name: 'qTransfer', url: 'https://transfer-cv5.pages.dev/', description: 'Easily connects 2 browsers to transfer files', category: 'Utilities' },
  { name: 'Readest', url: 'https://web.readest.com/', description: 'Ebook reader designed for immersive and deep reading experiences', category: 'Utilities', starred: true },
  { name: 'Relay', url: 'https://relay.rishishah.in', description: 'WebRTC peer-to-peer file transfer', category: 'Utilities' },
  { name: 'Sarx', url: 'https://www.sarx.app', description: 'Track stats, analyze your health values, and set targets.', category: 'Utilities' },
  { name: 'Sharr', url: 'https://www.sharrr.com/', description: 'End-to-end encrypted file transfer', category: 'Utilities' },
  { name: 'Spliit', url: 'https://spliit.app/', description: 'Share expenses with your friends and family', category: 'Utilities' },
  { name: 'Terminal.sexy', url: 'https://terminal.sexy', description: 'A terminal theme designer', category: 'Utilities' },
  { name: 'Texturinator', url: 'https://texturinator.buttermilch-dev.de/', description: 'Procedural texture and volume generation toolkit', category: 'Utilities' },
  { name: 'ToolsAtZero', url: 'https://www.toolsatzero.com/', description: 'A workbench of 52 everyday utilities running client-side', category: 'Utilities' },
  { name: 'Ul0', url: 'https://ul0.site', description: 'Free URL shortener that lets you create branded short links.', category: 'Utilities' },
  { name: 'VERT', url: 'https://vert.sh/', description: 'File-converter fully in-browser', category: 'Utilities' },
  { name: 'Webtor.io', url: 'https://webtor.io/', description: 'Seamless torrent streaming and file sharing', category: 'Utilities', starred: true },
  { name: 'xipe', url: 'https://xi.pe/', description: 'URL shortener and pastebin service', category: 'Utilities' },
  { name: 'zkdrop', url: 'https://zkdrop.org', description: 'Temporary file sharing with zero-knowledge encryption', category: 'Utilities' },

  // Data & Analytics
  { name: 'Datasette Lite', url: 'https://lite.datasette.io', description: 'Datasette Python web application running directly in your browser.', category: 'Data & Analytics' },
  { name: 'Grade Boundaries', url: 'https://gradeboundaries.com', description: 'A level and IGCSE grade boundary lookup', category: 'Data & Analytics' },
  { name: 'Mr. Data Converter', url: 'https://shancarter.github.io/mr-data-converter/', description: 'Converts Excel/CSV data into JSON, XML, and other web formats.', category: 'Data & Analytics' },
  { name: 'OSIRIS', url: 'https://www.osirisai.live/', description: 'Open Source Palantir Alternative', category: 'Data & Analytics' },
  { name: 'RAWGraphs', url: 'https://app.rawgraphs.io', description: 'Create custom vector-based visualizations on top of your data.', category: 'Data & Analytics' },
  { name: 'Satvisor', url: 'https://satvisor.com/', description: '3D satellite tracker with orbit visualization', category: 'Data & Analytics' },
  { name: 'Schema3D', url: 'https://schema3d.com/', description: 'An interactive tool for visualizing relational database schemas in 3D.', category: 'Data & Analytics' },
  { name: 'SQLChef', url: 'https://jonathanwalker.github.io/SQLChef/', description: 'Query CSV, JSON, and Parquet files directly in the browser', category: 'Data & Analytics' },
  { name: 'World Monitor', url: 'https://www.worldmonitor.app/', description: 'Real-time global intelligence dashboard and situations monitor.', category: 'Data & Analytics' },

  // Media
  { name: 'AudioMass', url: 'https://audiomass.co/', description: 'Free full-featured web-based audio & waveform editing tool', category: 'Media', starred: true },
  { name: 'ClearCanvas AI', url: 'https://clearcanvasai.vercel.app/', description: 'Generate, compress, upscale pictures, and remove backgrounds.', category: 'Media' },
  { name: 'Cobalt', url: 'https://cobalt.tools/', description: 'Media downloader without ads, trackers, paywalls, or nonsense.', category: 'Media' },
  { name: 'ComposeYogi', url: 'https://composeyogi.com/', description: 'Ableton-style music composer for the web', category: 'Media', starred: true },
  { name: 'Compress', url: 'https://videocompress.prolab.sh/', description: 'Crush video sizes by 90% with no quality loss offline.', category: 'Media' },
  { name: 'Drumhaus', url: 'https://drumha.us/', description: 'Computer Controlled Rhythmic Groove Machine', category: 'Media' },
  { name: 'FreeCut', url: 'https://freecut.net', description: 'Professional video editing in your browser with zero installation.', category: 'Media' },
  { name: 'GreenDolphin', url: 'https://greendolph.in', description: 'Recording looper and song transcription tool for musicians.', category: 'Media' },
  { name: 'Image Max URL', url: 'https://qsniyg.github.io/maxurl/', description: 'Finds larger/original versions of images and videos', category: 'Media' },
  { name: 'Midee', url: 'https://midee.app/', description: 'Play, visualize, learn, and export your MIDI music as piano-roll videos.', category: 'Media', starred: true },
  { name: 'MiNi PhotoEditor', url: 'https://mini2-photo-editor.netlify.app/', description: 'Online WebGL photo editor with effects, filters, and cropping', category: 'Media' },
  { name: 'OmniClip', url: 'https://omniclip.app/', description: 'Powerful video editor right in your browser', category: 'Media' },
  { name: 'OpenCut', url: 'https://opencut.app', description: 'The open-source CapCut alternative', category: 'Media', starred: true },
  { name: 'OpenReel', url: 'https://openreel.video/', description: 'Open source CapCut alternative', category: 'Media' },
  { name: 'Openvid', url: 'https://openvid.dev/en', description: 'Transform raw screen recordings into polished demonstration videos.', category: 'Media', starred: true },
  { name: 's-2-v', url: 'https://s-2-v.pages.dev/', description: 'A simple collection of video processing tools', category: 'Media' },
  { name: 'Squoosh', url: 'https://squoosh.app/', description: 'Image compression web app that reduces image sizes through numerous formats', category: 'Media' },
  { name: 'SubtitleEdit', url: 'https://www.nikse.dk/subtitleedit/online', description: 'Online Subtitle Editor', category: 'Media' },
  { name: 'Wavacity', url: 'https://wavacity.com/', description: 'Easy-to-use, multi-track audio editor and recorder', category: 'Media' },

  // Education
  { name: 'Agora Cosmica', url: 'https://agoracosmica.org', description: 'Learn from historical figures through stories and AI conversation.', category: 'Education' },
  { name: 'Full Stack open', url: 'https://fullstackopen.com/en/', description: 'Learn React, Redux, Node.js, MongoDB, GraphQL and TypeScript', category: 'Education' },
  { name: 'Quizbun', url: 'https://a-dev.github.io/quizbun/', description: 'Explanation-first quiz catalog for self-learners.', category: 'Education' },
  { name: 'Roadmaps.sh', url: 'https://roadmap.sh/', description: 'Interactive roadmaps and educational guides for developers.', category: 'Education' },
  { name: 'The Missing Manual', url: 'https://themissingmanual.dev', description: 'In-depth guides to computers, network, database and AI structures.', category: 'Education' },

  // Lists
  { name: 'free-for.dev', url: 'https://free-for.dev/#/', description: 'A list of SaaS, PaaS and IaaS offerings with free tiers of interest.', category: 'Lists' },
  { name: 'freemediaheckyeah', url: 'https://fmhy.net/', description: 'The largest collection of free stuff on the internet!', category: 'Lists' },
  { name: 'OSINT Framework', url: 'https://osintframework.com/', description: 'Directory of OSINT tools and resources organized by category.', category: 'Lists' }
];

export const EXTERNAL_CATEGORIES = [
  'All',
  'Productivity',
  'Design & Graphics',
  'Development',
  'Writing & Docs',
  'Privacy & Security',
  'Utilities',
  'Data & Analytics',
  'Media',
  'Education',
  'Lists'
];
