export interface LibraryItem {
  name: string;
  url: string;
  subject?: string;
  desc: string;
}

export interface LibrarySection {
  title: string;
  emoji: string;
  count: number;
  items: LibraryItem[];
}

export const LIBRARY_SECTIONS: LibrarySection[] = [
  {
    title: 'General & Subject-Specific Digital Libraries',
    emoji: '📚',
    count: 130,
    items: [
      { name: 'Access to Insight', url: 'https://accesstoinsight.org/', subject: 'Theravada Buddhism', desc: 'Translated texts from the Tipitaka, and contemporary Buddhist materials.' },
      { name: 'Ahlul Bayt DILP', url: 'https://www.al-islam.org/', subject: 'Shia Islam', desc: 'Resources related to history, law, and society of the Islamic religion.' },
      { name: 'Aozora Bunko', url: 'https://www.aozora.gr.jp/', subject: 'Japanese', desc: 'Digitized Japanese language texts, free to read.' },
      { name: 'Arnetminer / AMiner', url: 'https://www.aminer.org/', subject: 'Computer Science', desc: 'Index and search academic social networks, hosted at Tsinghua University.' },
      { name: 'ArXiv', url: 'https://arxiv.org/', subject: 'Science', desc: 'Preprints in mathematics, physics, computer science, quantitative biology and statistics.' },
      { name: 'Authorama', url: 'http://www.authorama.com/', subject: 'General', desc: 'Public domain books presented for free online reading.' },
      { name: 'Avalon Project', url: 'https://avalon.law.yale.edu/', subject: 'Law & History', desc: 'Digital library of documents relating to law, history and diplomacy — Yale Law School.' },
      { name: 'Baen Free Library', url: 'https://www.baen.com/catalog/category/view/s/free-library/id/2012', subject: 'Sci-Fi & Fantasy', desc: 'Science fiction and fantasy from publishing house Baen Books.' },
      { name: 'Bartleby.com', url: 'https://www.bartleby.com/', subject: 'Literature', desc: 'Literature, reference and verse — one of the oldest public-domain libraries online.' },
      { name: 'Bibliomania', url: 'https://www.bibliomania.com/', subject: 'General', desc: 'Free online literature, study guides, and reference works.' },
      { name: 'Biodiversity Heritage Library', url: 'https://www.biodiversitylibrary.org/', subject: 'Natural History', desc: 'Open access digital library for biodiversity literature.' },
      { name: 'Bookshare', url: 'https://www.bookshare.org/cms/', subject: 'Accessible Books', desc: 'Accessible books (DAISY and BRF) for people with print disabilities.' },
      { name: 'British History Online', url: 'https://www.british-history.ac.uk/', subject: 'History', desc: 'Core printed primary and secondary sources for the medieval and modern history of the British Isles.' },
      { name: 'California Digital Library', url: 'https://cdlib.org/', subject: 'General', desc: 'Library, museum and cultural heritage treasures from California campuses.' },
      { name: 'Canadiana Online', url: 'https://www.canadiana.ca/', subject: 'Canada', desc: 'Canadian historical primary sources — books, newspapers, periodicals, and archival material.' },
      { name: 'Center for Research Libraries', url: 'https://www.crl.edu/', subject: 'General', desc: 'Rare research collections and archival material from global institutions.' },
      { name: 'CSNTM', url: 'https://www.csntm.org/', subject: 'New Testament', desc: 'Center for the Study of New Testament Manuscripts — preserves and studies NT manuscripts.' },
      { name: 'CVCE', url: 'https://www.cvce.eu/en', subject: 'European History', desc: 'Digital library of multimedia resources related to European unification since WWII.' },
      { name: 'Chinese Text Project', url: 'https://ctext.org/', subject: 'Chinese Classics', desc: 'Electronic library of early Chinese texts.' },
      { name: 'Choral Public Domain Library', url: 'http://www.cpdl.org/wiki/', subject: 'Music', desc: 'Free choral/vocal scores, texts, translations, and other useful information.' },
      { name: 'Christian Classics Ethereal Library', url: 'https://www.ccel.org/', subject: 'Christian', desc: 'Digital library of hundreds of classic Christian books.' },
      { name: 'CiteSeerX', url: 'https://citeseerx.ist.psu.edu/', subject: 'Computer Science', desc: 'Scientific literature digital library and search engine hosted at Penn State.' },
      { name: 'Civil Rights Litigation Clearinghouse', url: 'https://www.clearinghouse.net/', subject: 'Civil Rights', desc: 'Documents and information from civil rights cases across the United States.' },
      { name: 'Classic Reader', url: 'https://www.classicreader.com/', subject: 'General', desc: 'Free classic literature available to read online.' },
      { name: 'DBLP Computer Science Bibliography', url: 'https://dblp.org/', subject: 'Computer Science', desc: 'Open bibliographic information on major computer science journals and proceedings.' },
      { name: 'Digital Book Index', url: 'http://www.digitalbookindex.org/', subject: 'General', desc: 'Index of tens of thousands of free and priced ebooks across categories.' },
      { name: 'Digital Comic Museum', url: 'https://digitalcomicmuseum.com/', subject: 'Comics', desc: 'Thousands of freely downloadable public domain Golden Age comics.' },
      { name: 'Digital Himalaya', url: 'http://www.digitalhimalaya.com/', subject: 'Himalayas', desc: 'Archives ethnographic materials from the Himalayan region.' },
      { name: 'Digital Public Library of America', url: 'https://dp.la/', subject: 'General', desc: 'Discover images, texts, videos, and sounds from across the United States.' },
      { name: 'Digital South Asia Library', url: 'https://dsal.uchicago.edu/index.html', subject: 'South Asia', desc: 'Materials for reference and research on South Asia.' },
      { name: 'Directory of Open Access Journals', url: 'https://doaj.org/', subject: 'General', desc: 'Over 20,000 peer-reviewed open access journals across all disciplines.' },
      { name: 'Distributed Proofreaders Canada', url: 'https://www.pgdpcanada.net/c/default.php', subject: 'Canada', desc: 'Volunteer initiative converting Canadian public domain books to electronic formats.' },
      { name: 'Domínio Público', url: 'http://www.dominiopublico.gov.br/pesquisa/PesquisaObraForm.jsp', subject: 'Brazil', desc: 'Literary, artistic and scientific works in the Brazilian public domain.' },
      { name: 'eGranary Digital Library', url: 'https://www.widernet.org/eGranary/', subject: 'Education', desc: 'Over 35 million resources: books, journals, websites, video, audio, software.' },
      { name: 'English Broadside Ballad Archive', url: 'http://ebba.english.ucsb.edu/', subject: 'Literature', desc: 'Online digital archive of 17th century English broadside ballads.' },
      { name: 'EuroDocs', url: 'https://eudocs.lib.byu.edu/index.php/Main_Page', subject: 'European History', desc: 'Facsimiles, transcriptions and translations of primary European historical documents.' },
      { name: 'Europeana', url: 'https://www.europeana.eu/en', subject: 'General', desc: 'Linking archives, libraries, museums and audio-visual material from across Europe.' },
      { name: 'FadedPage', url: 'https://www.fadedpage.com/', subject: 'Canada', desc: 'Public domain ebooks under Canadian copyright law.' },
      { name: 'Feedbooks Public Domain', url: 'https://www.feedbooks.com/publicdomain', subject: 'General', desc: 'Public domain ebook catalog available in multiple formats.' },
      { name: 'FRASER', url: 'https://fraser.stlouisfed.org/', subject: 'Economics', desc: 'Digital library of economic, financial and banking materials on US economic history.' },
      { name: 'Free-eBooks.net', url: 'https://www.free-ebooks.net/', subject: 'General', desc: 'Large catalog of free ebooks across genres (free account for downloads).' },
      { name: 'Full Books', url: 'http://www.fullbooks.com/', subject: 'General', desc: 'Free full-text classic books available online.' },
      { name: 'Gallica', url: 'https://gallica.bnf.fr/accueil/en/content/accueil-en', subject: 'French', desc: 'French national digital library — books, journals, manuscripts, images, maps, scores.' },
      { name: 'Girlebooks', url: 'https://girlebooks.com/', subject: 'Women Authors', desc: 'Free ebooks by female authors, primarily classic literature.' },
      { name: 'Global Grey Ebooks', url: 'https://www.globalgreyebooks.com/', subject: 'General', desc: 'Free public domain ebooks formatted and proofread for EPUB, PDF, and Kindle.' },
      { name: 'Google Books', url: 'https://books.google.com/', subject: 'General', desc: 'Search the world\'s most comprehensive index of full-text books.' },
      { name: 'Harvard University Library', url: 'https://library.harvard.edu/', subject: 'General', desc: 'Digitized collections spanning art, architecture, religion, history, culture, biology, music, law.' },
      { name: 'HathiTrust', url: 'https://www.hathitrust.org/', subject: 'General', desc: 'Partnership of academic institutions offering millions of digitized titles.' },
      { name: 'Heidelberg University Digital Library', url: 'https://www.ub.uni-heidelberg.de/', subject: 'General', desc: 'More than 143,000 full-text journals and 3,900 databases.' },
      { name: 'Hungarian Electronic Library', url: 'http://mek.oszk.hu/indexeng.phtml', subject: 'Hungarian', desc: 'One of the most significant text archives of the Hungarian webspace.' },
      { name: 'Ibiblio', url: 'https://www.ibiblio.org/', subject: 'General', desc: 'Eclectic collections catalog hosted and shared by contributors worldwide.' },
      { name: 'INSPIRE-HEP', url: 'https://inspirehep.net/', subject: 'Physics', desc: 'Scientific documents in the field of high energy physics.' },
      { name: 'International Dunhuang Project', url: 'http://idp.bl.uk/', subject: 'Manuscripts', desc: 'Conserves, catalogues and digitises manuscripts and artifacts from the Silk Road.' },
      { name: 'IMSLP', url: 'https://imslp.org/wiki/Main_Page', subject: 'Music', desc: 'International Music Score Library Project — sharing the world\'s public domain sheet music.' },
      { name: 'Internet Archive', url: 'https://archive.org/', subject: 'General', desc: 'Non-profit library of millions of free books, movies, software, music, and websites.' },
      { name: 'Internet History Sourcebooks', url: 'https://sourcebooks.fordham.edu/index.asp', subject: 'History', desc: 'Public domain and copy-permitted historical texts for educational use.' },
      { name: 'Internet Sacred Text Archive', url: 'https://www.sacred-texts.com/', subject: 'Religion', desc: 'Archive of public domain texts from spiritual and religious traditions worldwide.' },
      { name: 'JSTOR (Open Content)', url: 'https://www.jstor.org/', subject: 'General', desc: 'Page image archive of scholarly journals; some content free, most requires institutional access.' },
      { name: 'L\'Association des Bibliophiles Universels', url: 'http://abu.cnam.fr/', subject: 'French', desc: 'Digitizes French texts in the public domain.' },
      { name: 'LacusCurtius', url: 'https://penelope.uchicago.edu/Thayer/E/home.html', subject: 'Classical Studies', desc: 'Ancient Rome texts and archaeology from the University of Chicago.' },
      { name: 'Library of Economics and Liberty', url: 'https://www.libertyfund.org/', subject: 'Economics', desc: 'Educational foundation fostering discussion of issues pertaining to liberty.' },
      { name: 'LibriVox', url: 'https://librivox.org/', subject: 'Audiobooks', desc: 'Free public domain audiobooks read by volunteers, mostly in English.' },
      { name: 'Literary Kicks', url: 'https://litkicks.com/', subject: 'General', desc: 'Fiction, poetry, philosophy, music, art, politics, history and pop culture.' },
      { name: 'Loyal Books', url: 'https://www.loyalbooks.com/', subject: 'Audiobooks', desc: 'Free public domain audiobooks and ebooks.' },
      { name: 'Ludwig von Mises Institute', url: 'https://mises.org/', subject: 'Economics', desc: 'Libertarian and Austrian School economics resources.' },
      { name: 'ManyBooks', url: 'https://manybooks.net/', subject: 'General', desc: 'Free ebook library offering thousands of public domain and free-license titles.' },
      { name: 'Marefa', url: 'https://www.marefa.org/', subject: 'Arabic', desc: 'Digitizes Arabic classics and other classics written in Arabic script.' },
      { name: 'Marxists Internet Archive', url: 'https://www.marxists.org/', subject: 'Political Theory', desc: 'Multilingual digital library of works by Marxist, communist, socialist and anarchist writers.' },
      { name: 'Maryland Digital Cultural Heritage', url: 'https://www.digitalmaryland.org/', subject: 'History', desc: 'Photographs and documents detailing Maryland\'s history and places.' },
      { name: 'Miguel de Cervantes Virtual Library', url: 'http://www.cervantesvirtual.com/', subject: 'Spanish', desc: 'Dedicated to the dissemination of culture in Spanish.' },
      { name: 'Munsey\'s', url: 'https://www.munseys.com/', subject: 'General', desc: 'Free ebooks in multiple formats across many genres.' },
      { name: 'Mutopia Project', url: 'https://www.mutopiaproject.org/', subject: 'Music', desc: 'Free public domain and Creative Commons sheet music in PDF, MIDI, LilyPond.' },
      { name: 'National Academies Press', url: 'https://www.nap.edu/', subject: 'General', desc: 'Reports and books from the National Academies of Sciences, Engineering, and Medicine.' },
      { name: 'National Digital Library Program (LoC)', url: 'http://international.loc.gov/intldl/intldlhome.html', subject: 'General', desc: 'Multilingual, multimedia digital libraries built with international partners by the Library of Congress.' },
      { name: 'National Electronic Library (Russia)', url: 'https://rusneb.ru/', subject: 'Russian', desc: 'Books, newspapers and magazines from Russian libraries.' },
      { name: 'New Advent', url: 'https://www.newadvent.org/', subject: 'Catholic', desc: 'Catholic Encyclopedia, Summa Theologica, Church Fathers, papal encyclicals.' },
      { name: 'New Zealand Electronic Text Centre', url: 'http://nzetc.victoria.ac.nz/', subject: 'New Zealand', desc: 'Significant New Zealand and Pacific Island texts and materials.' },
      { name: 'Online Books Page (UPenn)', url: 'http://onlinebooks.library.upenn.edu/', subject: 'General', desc: 'Extensive list of digital books available online — maintained by UPenn.' },
      { name: 'Open Culture Free Ebooks', url: 'https://www.openculture.com/free_ebooks', subject: 'General', desc: 'Curated collection of free ebooks, audiobooks, and courses.' },
      { name: 'Open Library', url: 'https://openlibrary.org/', subject: 'General', desc: 'Open, editable library catalog building toward a web page for every book ever published.' },
      { name: 'Oxford Text Archive', url: 'https://ota.bodleian.ox.ac.uk/repository/xmlui/', subject: 'Literature & Linguistics', desc: 'Repository of full-text literary and linguistic resources in more than 25 languages.' },
      { name: 'Pandora Archive', url: 'http://pandora.nla.gov.au/', subject: 'Australia', desc: 'Collection of web content about Australian life, society and landmark events.' },
      { name: 'Panjab Digital Library', url: 'http://panjabdigilib.org/webuser/searches/mainpage.jsp', subject: 'Punjabi', desc: 'Digitizes and preserves the cultural heritage of Punjab.' },
      { name: 'Paperity', url: 'https://paperity.org/', subject: 'General', desc: 'Aggregator of open access scholarly journals across all academic disciplines.' },
      { name: 'Perseus Project', url: 'http://www.perseus.tufts.edu/hopper/', subject: 'Classics', desc: 'Covers the history, literature and culture of the Greco-Roman world.' },
      { name: 'PGDP (Distributed Proofreaders)', url: 'https://www.pgdp.net/', subject: 'General', desc: 'Volunteer proofreading project supplying texts to Project Gutenberg.' },
      { name: 'Project Gutenberg', url: 'https://gutenberg.org/', subject: 'General', desc: 'Founded in 1971 — the first project to create a library of freely available online texts.' },
      { name: 'Project Gutenberg Australia', url: 'https://gutenberg.net.au/', subject: 'Australia', desc: 'Provides texts under Australian copyright law.' },
      { name: 'Project Gutenberg Canada', url: 'http://gutenberg.ca/index.html', subject: 'Canada', desc: 'Provides texts under Canadian copyright law.' },
      { name: 'Project Madurai', url: 'https://www.projectmadurai.org/', subject: 'Tamil', desc: 'A collection of Tamil literature.' },
      { name: 'Project Noolaham', url: 'https://noolahamfoundation.org/web/', subject: 'Sri Lankan Tamil', desc: 'Digital archive documenting Sri Lankan Tamil-speaking communities\' cultural heritage.' },
      { name: 'Project Runeberg', url: 'http://runeberg.org/', subject: 'Nordic', desc: 'Volunteer effort creating free electronic editions of classic Nordic literature.' },
      { name: 'Rare Book Room', url: 'http://www.rarebookroom.org/', subject: 'General', desc: 'Educational site to examine and read some of the world\'s great books.' },
      { name: 'Read Print', url: 'https://www.readprint.com/', subject: 'General', desc: 'Free online books and texts, mostly classic literature.' },
      { name: 'Russian State Library', url: 'https://www.rsl.ru/en', subject: 'Russian', desc: 'Bibliographic records covering items published in Russian and other languages.' },
      { name: 'SciELO', url: 'https://scielo.org/en/', subject: 'Science', desc: 'Multidisciplinary repository for research data and journals, mainly from Latin America.' },
      { name: 'Sefaria', url: 'https://www.sefaria.org/texts', subject: 'Jewish Texts', desc: 'Free-content digital library of Jewish texts.' },
      { name: 'South Asian American Digital Archive', url: 'https://www.saada.org/', subject: 'South Asian American', desc: 'Documents and preserves the material history of the South Asian American community.' },
      { name: 'Standard Ebooks', url: 'https://standardebooks.org/', subject: 'General', desc: 'Volunteer-driven collection of high-quality, carefully formatted public domain ebooks.' },
      { name: 'Text Creation Partnership', url: 'https://textcreationpartnership.org/', subject: 'Humanities', desc: 'Produces large-scale full-text electronic resources, especially in the humanities.' },
      { name: 'Textos.info', url: 'https://www.textos.info/', subject: 'Spanish', desc: 'Open virtual library for public domain and Creative Commons books written in Spanish.' },
      { name: 'The Complete Works of Charles Darwin Online', url: 'http://darwin-online.org.uk/', subject: 'Biology', desc: 'The world\'s largest and most widely used resource on Charles Darwin.' },
      { name: 'The Kurdish Digital Library', url: 'https://bnk.institutkurde.org/?l=en', subject: 'Kurdish Heritage', desc: 'Writings about the Kurds and Kurdistan, digitizing Kurdish cultural heritage.' },
      { name: 'The Latin Library', url: 'https://www.thelatinlibrary.com/', subject: 'Latin', desc: 'Scanned and formatted Latin texts from the public domain.' },
      { name: 'Traditional Knowledge Digital Library', url: 'http://www.tkdl.res.in/tkdl/langdefault/common/Home.asp', subject: 'Indian Heritage', desc: 'Repository protecting India\'s traditional knowledge from unethical patenting.' },
      { name: 'UK Web Archive', url: 'https://www.webarchive.org.uk/', subject: 'UK', desc: 'Partnership of UK legal deposit libraries collecting UK websites annually.' },
      { name: 'US National Agricultural Library', url: 'https://www.nal.usda.gov/main/', subject: 'Agriculture', desc: 'One of the world\'s largest collections devoted to agriculture and related sciences.' },
      { name: 'US National Library of Medicine', url: 'https://www.nlm.nih.gov/', subject: 'Medicine', desc: 'Literature, sequence, and clinical studies information.' },
      { name: 'Wikibooks', url: 'https://www.wikibooks.org/', subject: 'General', desc: 'A digital library of open textbooks edited in a similar way to Wikipedia.' },
      { name: 'Wikisource', url: 'https://wikisource.org/wiki/Main_Page', subject: 'General', desc: 'A digital library of out-of-copyright or freely licensed source texts.' },
      { name: 'Wisconsin Historical Society', url: 'https://www.wisconsinhistory.org/', subject: 'History', desc: 'Wisconsin state, regional, and local history books, journals and museum collections.' },
      { name: 'World Digital Library (LoC)', url: 'https://www.wdl.org/en/', subject: 'General', desc: 'Project of the US Library of Congress and UNESCO with international contributions.' },
      { name: 'World eBook Library', url: 'http://worldlibrary.org/', subject: 'General', desc: 'Multilingual collection of public domain texts.' },
      { name: 'World Wide Web Virtual Library', url: 'http://vlib.org/', subject: 'General', desc: 'The oldest catalogue of the Web, started by Tim Berners-Lee in 1991.' },
      { name: 'Zeno.org', url: 'http://www.zeno.org/', subject: 'German', desc: 'German-language digital library covering literature, art and reference works.' },
    ]
  },
  {
    title: 'Academic & Scholarly Repositories',
    emoji: '🎓',
    count: 29,
    items: [
      { name: 'BASE (Bielefeld Academic Search Engine)', url: 'https://www.base-search.net/', desc: 'Indexes over 300 million documents from academic repositories worldwide.' },
      { name: 'bioRxiv', url: 'https://www.biorxiv.org/', desc: 'Free online archive and distribution service for unpublished preprints in the life sciences.' },
      { name: 'ChemRxiv', url: 'https://chemrxiv.org/', desc: 'Preprint server for chemistry.' },
      { name: 'CORE', url: 'https://core.ac.uk/', desc: 'Aggregates open access research outputs from repositories and journals worldwide.' },
      { name: 'Digital Commons Network', url: 'https://network.bepress.com/', desc: 'Free full-text scholarly articles from hundreds of universities and colleges worldwide.' },
      { name: 'DOAB', url: 'https://www.doabooks.org/', desc: 'Directory of Open Access Books — searchable directory of peer-reviewed open-access academic books.' },
      { name: 'DTIC', url: 'https://discover.dtic.mil/', desc: 'Defense Technical Information Center — US DoD repository of research and engineering reports.' },
      { name: 'ERIC', url: 'https://eric.ed.gov/', desc: 'US Department of Education\'s digital library of education research and information.' },
      { name: 'Europe PMC', url: 'https://europepmc.org/', desc: 'Europe\'s free full-text archive of biomedical and life sciences literature.' },
      { name: 'Google Scholar', url: 'https://scholar.google.com/', desc: 'Search engine indexing scholarly literature across disciplines and formats.' },
      { name: 'JURN', url: 'https://www.jurn.org/', desc: 'Search engine indexing free and open access journals and theses.' },
      { name: 'medRxiv', url: 'https://www.medrxiv.org/', desc: 'Preprint server for health sciences.' },
      { name: 'NASA Astrophysics Data System', url: 'https://ui.adsabs.harvard.edu/', desc: 'Digital library for research in astronomy and physics.' },
      { name: 'NASA Technical Reports Server', url: 'https://ntrs.nasa.gov/', desc: 'NASA\'s collection of aerospace research and technical reports.' },
      { name: 'NBER Working Papers', url: 'https://www.nber.org/papers', desc: 'Economic research, working papers, and public-facing data resources.' },
      { name: 'OAIster', url: 'https://oaister.on.worldcat.org/', desc: 'Union catalog of over 50 million records representing open access resources.' },
      { name: 'OAPEN Library', url: 'https://www.oapen.org/', desc: 'Open access platform for academic books, mainly in humanities and social sciences.' },
      { name: 'OpenAIRE Explore', url: 'https://explore.openaire.eu/', desc: 'Searches open research outputs, datasets, software, grants, and organizations.' },
      { name: 'OpenAlex', url: 'https://openalex.org/', desc: 'Open scholarly index of publications, authors, institutions, funders, and topics.' },
      { name: 'OpenDOAR', url: 'https://v2.sherpa.ac.uk/opendoar/', desc: 'Global directory of academic open access repositories.' },
      { name: 'PhilPapers', url: 'https://philpapers.org/', desc: 'Comprehensive index and bibliography of philosophy research.' },
      { name: 'PubMed', url: 'https://pubmed.ncbi.nlm.nih.gov/', desc: 'Over 36 million citations for biomedical and life sciences literature from MEDLINE.' },
      { name: 'PubMed Central (PMC)', url: 'https://www.ncbi.nlm.nih.gov/pmc/', desc: 'Free full-text archive of biomedical and life sciences journal literature.' },
      { name: 'RePEc / IDEAS', url: 'https://ideas.repec.org/', desc: 'Index to economics research created by volunteers worldwide.' },
      { name: 'ResearchGate (public content)', url: 'https://www.researchgate.net/', desc: 'Network where researchers share papers; full use benefits from a free account.' },
      { name: 'Semantic Scholar', url: 'https://www.semanticscholar.org/', desc: 'AI-powered research tool that filters relevant studies and highlights citations.' },
      { name: 'SSRN', url: 'https://www.ssrn.com/', desc: 'Open access repository of abstracts and papers by social science researchers.' },
      { name: 'Unpaywall', url: 'https://unpaywall.org/', desc: 'Database that finds free, legal full-text versions of paywalled research articles.' },
      { name: 'World Bank Open Knowledge Repository', url: 'https://openknowledge.worldbank.org/', desc: 'Open access repository of World Bank research and knowledge products.' },
    ]
  },
  {
    title: 'National & Regional Digital Libraries',
    emoji: '🏛️',
    count: 16,
    items: [
      { name: 'Biblioteca Digital do Mundo Ibero-Americano', url: 'http://www.iberoamericadigital.net/', desc: 'Portal linking digital resources of Ibero-American national libraries.' },
      { name: 'Biblioteca Digital Hispánica', url: 'http://www.bne.es/', desc: 'Digital collections of the National Library of Spain.' },
      { name: 'Biblioteca Nacional Digital (Portugal)', url: 'https://www.bnportugal.gov.pt/', desc: 'Digital collections of the National Library of Portugal.' },
      { name: 'British Library Digital Collections', url: 'https://www.bl.uk/collection-guides/digital-collections', desc: 'Digitized manuscripts, maps, sound, and images from the British Library.' },
      { name: 'China National Digital Library', url: 'http://www.nlc.cn/', desc: 'Digital collections from the National Library of China.' },
      { name: 'Deutsche Digitale Bibliothek', url: 'https://www.deutsche-digitale-bibliothek.de/', desc: 'German national digital library aggregating culture and science collections.' },
      { name: 'Digital Library of India', url: 'https://www.ndl.gov.in/', desc: 'National Digital Library of India — a repository of academic content across levels.' },
      { name: 'DigitalNZ', url: 'https://digitalnz.org/', desc: 'Aggregates content from New Zealand libraries, museums, and archives.' },
      { name: 'Library and Archives Canada', url: 'https://www.bac-lac.gc.ca/', desc: 'Canada\'s national archive and library of documentary heritage.' },
      { name: 'Nasjonalbiblioteket (Norway)', url: 'https://www.nb.no/', desc: 'Digitized Norwegian books, newspapers, and media, most viewable freely from Norway.' },
      { name: 'Nationaal Archief (Netherlands)', url: 'https://www.nationaalarchief.nl/', desc: 'The Dutch National Archives\' digitized historical collections.' },
      { name: 'National Diet Library (Japan)', url: 'https://dl.ndl.go.jp/', desc: 'Digitized Japanese books, periodicals, rare materials, and historical documents.' },
      { name: 'National Library Board Singapore', url: 'https://www.nlb.gov.sg/', desc: 'Digitized newspapers, maps, images, and historical documents of Singapore.' },
      { name: 'National Library of Medicine Digital Collections', url: 'https://www.nlm.nih.gov/hmd/collections/index.html', desc: 'Historical medical texts, images and manuscripts from the US National Library of Medicine.' },
      { name: 'National Library of Scotland Digital Gallery', url: 'https://digital.nls.uk/', desc: 'Digitized maps, manuscripts, and printed materials from Scotland\'s national library.' },
      { name: 'Trove (National Library of Australia)', url: 'https://trove.nla.gov.au/', desc: 'Searches billions of records — books, newspapers, images, maps, theses — from Australian institutions.' },
    ]
  },
  {
    title: 'Open Textbooks, Courseware & Education',
    emoji: '📖',
    count: 10,
    items: [
      { name: 'CK-12', url: 'https://www.ck12.org/', desc: 'Free K-12 textbooks, adaptive practice, and multimedia content.' },
      { name: 'Directory of Open Access Textbooks', url: 'https://www.oatext.org/', desc: 'Directory of freely available, openly licensed textbooks.' },
      { name: 'LibreTexts', url: 'https://libretexts.org/', desc: 'Open-access textbook library across STEM, humanities, and social sciences.' },
      { name: 'MERLOT', url: 'https://www.merlot.org/', desc: 'Curated online learning materials and support for higher education faculty.' },
      { name: 'MIT OpenCourseWare', url: 'https://ocw.mit.edu/', desc: 'Free lecture notes, exams, and videos from MIT courses.' },
      { name: 'OER Commons', url: 'https://www.oercommons.org/', desc: 'Digital library of open educational resources across subjects and grade levels.' },
      { name: 'OpenLearn (Open University)', url: 'https://www.open.ac.uk/openlearn/', desc: 'Free courses and learning resources from the UK\'s Open University.' },
      { name: 'OpenStax', url: 'https://openstax.org/', desc: 'Free, peer-reviewed, openly licensed college and AP textbooks.' },
      { name: 'Project MUSE (Open Access)', url: 'https://muse.jhu.edu/', desc: 'Some open access books and journals in humanities and social sciences.' },
      { name: 'Saylor Academy', url: 'https://www.saylor.org/', desc: 'Free self-paced online courses with open educational materials.' },
    ]
  },
  {
    title: 'Open Image, Sound, Font & Media Libraries',
    emoji: '🖼️',
    count: 14,
    items: [
      { name: 'Free Music Archive', url: 'https://freemusicarchive.org/', desc: 'Library of freely downloadable, legal audio curated by radio stations and curators.' },
      { name: 'Freesound', url: 'https://freesound.org/', desc: 'Collaborative database of Creative Commons-licensed sound clips.' },
      { name: 'Google Fonts', url: 'https://fonts.google.com/', desc: 'Free, open-source font library for use in any project.' },
      { name: 'Internet Archive Audio Archive', url: 'https://archive.org/details/audio', desc: 'Free music, audiobooks, and historical audio recordings.' },
      { name: 'Internet Archive Movie Archive', url: 'https://archive.org/details/movies', desc: 'Free public domain and historical films and video.' },
      { name: 'Metropolitan Museum of Art Open Access', url: 'https://www.metmuseum.org/art/collection', desc: 'Open access images of public domain artworks from the Met\'s collection.' },
      { name: 'NASA Image and Video Library', url: 'https://images.nasa.gov/', desc: 'Free-to-use archive of NASA images, videos, and audio.' },
      { name: 'Pexels', url: 'https://www.pexels.com/', desc: 'Free stock photo and video library.' },
      { name: 'Pixabay', url: 'https://pixabay.com/', desc: 'Free images, videos, and music released under a permissive license.' },
      { name: 'Rijksmuseum Rijksstudio', url: 'https://www.rijksmuseum.nl/en/rijksstudio', desc: 'High-resolution open access images of the Rijksmuseum\'s art collection.' },
      { name: 'Smithsonian Open Access', url: 'https://www.si.edu/openaccess', desc: 'Millions of 2D and 3D images and data from the Smithsonian\'s collections.' },
      { name: 'The Noun Project (free tier)', url: 'https://thenounproject.com/', desc: 'Large library of icons, many available free with attribution.' },
      { name: 'Unsplash', url: 'https://unsplash.com/', desc: 'High-resolution free-to-use photography library.' },
      { name: 'Wikimedia Commons', url: 'https://commons.wikimedia.org/', desc: 'Freely usable photos, illustrations, audio, and video files.' },
    ]
  },
  {
    title: 'Law, Government & Reference',
    emoji: '⚖️',
    count: 5,
    items: [
      { name: 'Cornell Legal Information Institute (LII)', url: 'https://www.law.cornell.edu/', desc: 'Free access to US federal and state law, codes, and court opinions.' },
      { name: 'FAO Digital Library', url: 'https://www.fao.org/documents/', desc: 'UN Food and Agriculture Organization\'s repository of reports and data.' },
      { name: 'GovInfo', url: 'https://www.govinfo.gov/', desc: 'Official US federal government publications, laws, and congressional records.' },
      { name: 'UN Digital Library', url: 'https://digitallibrary.un.org/', desc: 'United Nations documents, resolutions, and publications.' },
      { name: 'WHO IRIS Repository', url: 'https://iris.who.int/', desc: 'WHO\'s institutional repository of health reports and publications.' },
    ]
  },
];
